### ISSUE TITLE
Model not feasible

### ISSUE THREAD

**Issue by ACE07-Sev** [Maldini32/DWAVE4TSPLIB#1]
Hi there, I ran the model, and it plotted this as the result :
![image](https://user-images.githubusercontent.com/73689800/171616352-c7e8787c-70d0-47eb-b89c-891231e4ffe6.png)
Which is I think wrong as it doesn't cover node 9, and also not sure if this is the optimal solution (or essentially what is expected).

Could you kindly clarify on this?

**Comment by ACE07-Sev** [comment]
I tried to decomment the following lines in dwave_tsp_solver :
 def solve_tsp(self):
        response = EmbeddingComposite(
            DWaveSampler(token=self.sapi_token, endpoint=self.url, solver='DW_2000Q_5')).sample_qubo(self.qubo_dict,
                                                                                                     chain_strength=self.chainstrength,
                                                                                                     num_reads=self.numruns)
        sampler = EmbeddingComposite(DWaveSampler(token=self.sapi_token, endpoint=self.url, solver='DW_2000Q_5'))
        # response = QBSolv().sample_qubo(Q, solver=sampler, solver_limit=subqubo_size)
        subqubo_size = 6
        # response = QBSolv().sample_qubo(self.qubo_dict, chain_strength=self.chainstrength, num_reads=self.numruns, solver_limit=subqubo_size)

        self.decode_solution(response)
        return self.solution, self.distribution

Kindly confirm if I have decommented correctly.
This is the error I am getting :
Traceback (most recent call last):
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dwave\cloud\client\base.py", line 782, in _fetch_solvers
    data = Client._sapi_request(self.session.get, url)
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dwave\cloud\client\base.py", line 1794, in _sapi_request
    raise SolverError(error_msg=error_msg, error_code=error_code)
dwave.cloud.exceptions.SolverError: Solver does not exist or apitoken does not have access

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\elmm\Desktop\CQM\TSP_Dwave\DWAVE4TSPLIB-master\src\main.py", line 43, in <module>
    solveTSPinstance("data/burma14.tsp")
  File "C:\Users\elmm\Desktop\CQM\TSP_Dwave\DWAVE4TSPLIB-master\src\main.py", line 29, in solveTSPinstance
    dwave_solution, dwave_distribution = dwave_solver.solve_tsp()
  File "C:\Users\elmm\Desktop\CQM\TSP_Dwave\DWAVE4TSPLIB-master\src\dwave_tsp_solver.py", line 73, in solve_tsp
    DWaveSampler(token=self.sapi_token, endpoint=self.url, solver='DW_2000Q_5')).sample_qubo(self.qubo_dict,
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dwave\system\samplers\dwave_sampler.py", line 143, in __init__
    self.solver = self.client.get_solver()
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dwave\cloud\client\base.py", line 1250, in get_solver
    solvers = self.get_solvers(refresh=refresh, order_by=order_by, **filters)
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dwave\cloud\events.py", line 105, in wrapped
    rval = fn(*pargs, **kwargs)
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dwave\cloud\client\base.py", line 1148, in get_solvers
    solvers = self._fetch_solvers(**query)
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dwave\cloud\utils.py", line 463, in wrapper
    val = fn(*args, **kwargs)
  File "C:\Users\elmm\AppData\Local\Programs\Python\Python39\lib\site-packages\dwave\cloud\client\base.py", line 785, in _fetch_solvers
    raise SolverNotFoundError("No solver with name={!r} available".format(name))
dwave.cloud.exceptions.SolverNotFoundError: No solver with name='DW_2000Q_5' available

**Comment by ACE07-Sev** [comment]
Model even on QPU is still not feasible. I suppose this is due to how the QUBO is being defined. Perhaps a CQM would be more appropriate?
![image](https://user-images.githubusercontent.com/73689800/171640743-081d4e57-b689-4182-a6ab-7278550cfee2.png)
